[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Atelier-cave-Dark_edit
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Atelier-cave-Dark_edit
GtkTheme=oomox-Atelier-cave-Dark_edit
IconTheme=oomox-Atelier-cave-Dark_edit
MetacityTheme=oomox-Atelier-cave-Dark_edit
